#!/usr/bin/env bash
# Generated by Matugen — Dynamically updates River window borders

# 1. Update active border color using your primary color hex code
riverctl border-color-focused "0x{{colors.primary.default.hex.strip}}ff"

# 2. Update inactive border color using your highest surface container color hex code
riverctl border-color-unfocused "0x{{colors.surface_container_highest.default.hex.strip}}ff"
